// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3bY3N2o3CT6V-zjD9spnds8NO20XIybQ',
    appId: '1:355375002359:web:8dfbee8d2dbca66dabd9f2',
    messagingSenderId: '355375002359',
    projectId: 'appdata-flutter',
    authDomain: 'appdata-flutter.firebaseapp.com',
    storageBucket: 'appdata-flutter.appspot.com',
    measurementId: 'G-9V1TFR1L19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1InC25H_ELGFlMkUD7NPpPedwk1A2zSc',
    appId: '1:355375002359:android:bd0632ed6419d91babd9f2',
    messagingSenderId: '355375002359',
    projectId: 'appdata-flutter',
    storageBucket: 'appdata-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9f7l19N8Xv3AFYpawLx62RC2Bk99BnGQ',
    appId: '1:355375002359:ios:34bba4e65e01db18abd9f2',
    messagingSenderId: '355375002359',
    projectId: 'appdata-flutter',
    storageBucket: 'appdata-flutter.appspot.com',
    iosBundleId: 'com.example.appdata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9f7l19N8Xv3AFYpawLx62RC2Bk99BnGQ',
    appId: '1:355375002359:ios:34bba4e65e01db18abd9f2',
    messagingSenderId: '355375002359',
    projectId: 'appdata-flutter',
    storageBucket: 'appdata-flutter.appspot.com',
    iosBundleId: 'com.example.appdata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3bY3N2o3CT6V-zjD9spnds8NO20XIybQ',
    appId: '1:355375002359:web:30d875a27f264124abd9f2',
    messagingSenderId: '355375002359',
    projectId: 'appdata-flutter',
    authDomain: 'appdata-flutter.firebaseapp.com',
    storageBucket: 'appdata-flutter.appspot.com',
    measurementId: 'G-YXYBZPTWQC',
  );
}
